apiVersion: v1
kind: ConfigMap
metadata:
  name: kuzora-face-verification-configmap
data:
  config_path: /app/src/config/config-kube.yml
  pythonpath: /app/src
  alembic_config: /app/alembic_kube.ini
