apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuzora-face-verification-deployment
spec:
  replicas: 1
  selector:
    matchLables:
      app: kuzora-face-verification
  template:
    metadata:
      labels:
        app: kuzora-face-verification
    spec:
      containers:
        - name: kuzora-face-verification
          image: ...
          resourses:
            limits:
              memory: "200Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_PATH
              valueFrom:
                configMapKeyRef:
                  name: kuzora-face-verification-configmap
                  key: config_path
            - name: PYTHONPATH
              valueFrom:
                configMapKeyRef:
                  name: kuzora-face-verification-configmap
                  key: pythonpath
