apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuzora-vectors-pvc
spec:
  storageClassName: yc-network-hdd
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
