apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuzora-vectors-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: "stable"
