kafka:
  host: "kafka"
  port: 9092
  file_encoding: "utf-8"
  file_compression_quality: 1
  storage_path: "/var/www/face_verification/vectors"
  topics: "faces"
postgres:
  pg_dns: "postgresql+psycopg2://myuser:mysecretpassword@db:5432/mydatabase"
  pool_size: 10
  max_overflow: 20
monitoring:
  metrics:
    enabled: False
